#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_REPO=christopher102994
  - DOCKER_NAME=docker-base-img
  - DOCKER_TAG=alpine-3.10

before_install:
        provider: script
        script: bash ci/make_container.sh
        on:
                branch: master
deploy:
        provider: script
        script: bash ci/push_to_registry.sh
        on:
                branch: master
