#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

language: generic

services:
  - docker

env:
  global:
  - DOCKER_REPO=christopher102994
  - DOCKER_NAME=docker-base-img
  - DOCKER_TAG=alpine-3.10

script:
  - ci/make_container.sh

deploy:
  - ci/push_to_registry.sh

