#
# Travis CI file to build, test and push docker images to the Docker Hub.
#

language: generic

os:
  - linux

services:
  - docker

git:
  submodules: true

env:
  global:
  - DOCKER_REPO=christopher102994
  - DOCKER_NAME=docker-base-img

jobs:
  include:
  - stage: Alpine Container
    env:
      - VERSION_FILE=versions/alpine-3.10.env
    script:
      - source tools/scripts/load_env_files.sh $VERSION_FILE
      - source tools/scripts/versioning.sh 
      - tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh
        
  - stage: Debian Container
    env:
      - VERSION_FILE=versions/debian-10.env
    script:
      - source tools/scripts/load_env_files.sh $VERSION_FILE
      - source tools/scripts/versioning.sh 
      - tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh

  - stage: Ubuntu Container
    env:
      - VERSION_FILE=versions/ubuntu-18.env
    script:
      - source tools/scripts/load_env_files.sh $VERSION_FILE
      - source tools/scripts/versioning.sh 
      - tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh

  - stage: Git Tag
    script: 
      - source tools/scripts/versioning.sh
      - tools/scripts/push_git_tag.sh
