#!/usr/bin/with-contenv bash

. pkg-manager

case "$MANAGER" in
                apt-get )
                    exec /usr/sbin/cron -f -L 4
                    ;;
                apk )
					exec /usr/sbin/crond -f -S -l 5 -c /etc/crontabs
                    ;;
                *)
                    ;;
esac

