#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error

# Ensure Data folder Exists
DATA_PATH='/config/data'
if [ ! -d $DATA_PATH ]; then
	log $(basename $0) "First boot with mounted /config/data detected."
	mkdir -p $DATA_PATH
fi


# Ensure Data folder Exists
LOG_PATH='/config/log'
if [ ! -d $LOG_PATH ]; then
	log $(basename $0) "First boot with mounted /config/log detected."
	mkdir -p $LOG_PATH
fi

chown -R $USERNAME:$GROUPNAME /app
chown -R $USERNAME:$GROUPNAME /config
chown -R $USERNAME:$GROUPNAME /defaults

chmod -R 0755 /app
chmod -R 0755 /config
chmod -R 0755 /defaults