#!/usr/bin/with-contenv bash

echo "
-------------------------
# USER DEFINED VARIABLES:
-------------------------
$(printenv | grep -v "HOSTNAME" \
		   | grep -v "PWD" \
		   | grep -v "CWD" \
		   | grep -v "HOME" \
		   | grep -v "TERM" \
		   | grep -v "SHLVL" \
		   | grep -v "PATH" \
		   | grep -v "URL" \
		   | grep -v "VER" \
		   | grep -v "_=")
-------------------------
# UID/GID of $USERNAME:
-------------------------
UID: $(id -u $USERNAME)
GID: $(id -g $USERNAME)
-------------------------
# FOLDER PERMISSIONS:
-------------------------
$(ls -ld /app)
$(ls -ld /config)
$(ls -ld /defaults)
-------------------------"

